format = """$directory($style)\
$git_branch \
$python \
$cmd_duration\
$character """

[character]
success_symbol = "[λ  -->](bold #ec31e5)"
error_symbol = "[Xi -->](bold red)"

[directory]
truncation_length = 1
truncation_symbol = ""
style = "bold green"

[git_branch]
format = "git:\\([$branch]($style)\\)"
style = "bold #ff79c6"

[python]
format = "py:\\([$virtualenv]($style)\\)"
style = "bold yellow"
